### ISSUE TITLE
definition of **s_max** and **s** ?

### ISSUE THREAD

**Issue by mahmoudalbardan** [BayerSe/l1qr#5]
hello,
what is the difference (or definition) between **s_max** (in the fit method) and **s** (in the predict method)?
I understand that **s_max** is the regularization parameter the should be greater than the **l1-norm** of the coefficients vector, but i do not see what **s** stands for.

thanks

**Comment by BayerSe** [comment]
Hi,

`s_max` is used to prematurely stop the algorithm when `s` reaches `s_max`. In fact, `s` is the regularization parameter.
Does this help?

**Comment by mahmoudalbardan** [comment]
thanks for the details. 
However, I do not see why the regularization parameter `s` shows up in the  prediction phase (argument of the predict function) not during training (in the fit function).
As I understand it, the regularization parameter is only used when training to estimate the coefficients, not for prediction.

Another question: if we want to access the final estimated coefficients, we can do `mdl.beta[-1]` ?

**Comment by BayerSe** [comment]
The algorithm of Li and Zhu (2008) fits the whole path, i.e. for all values of `s`. Therefore, it does not show up in the `fit` function - the only thing you can can control is some premature stopping via `s_max`. When it comes to prediction you have to make a choice - for which value of `s` do you want to get the prediction? 

`mdl.beta[-1]` gives you the estimate of the coefficients for the largest value of `s` - which should be equivalent to the unpenalized QR estimator.

**Comment by mahmoudalbardan** [comment]
Thank you Bayer. 
It is more clear right now.

**Comment by BayerSe** [comment]
Great!
